/* oxlint-disable import/no-unassigned-import -- each module registers an editor feature for its side effect */
// The Monaco features the schema editor uses. Everything else of the editor (the other
// languages, the diff editor, the LSP client) stays out of the bundle.
// The core commands and controllers editor.main wires up outside the feature registers.
import 'monaco-editor/editor/browser/coreCommands.js'
import 'monaco-editor/editor/contrib/caretOperations/browser/caretOperations.js'
import 'monaco-editor/editor/contrib/dropOrPasteInto/browser/copyPasteContribution.js'
import 'monaco-editor/editor/contrib/gotoError/browser/markerSelectionStatus.js'
import 'monaco-editor/editor/contrib/suggest/browser/suggestController.js'
import 'monaco-editor/features/bracketMatching/register.js'
import 'monaco-editor/features/clipboard/register.js'
import 'monaco-editor/features/codeAction/register.js'
import 'monaco-editor/features/codicon/register.js'
import 'monaco-editor/features/comment/register.js'
import 'monaco-editor/features/contextmenu/register.js'
import 'monaco-editor/features/cursorUndo/register.js'
import 'monaco-editor/features/documentSymbols/register.js'
import 'monaco-editor/features/find/register.js'
import 'monaco-editor/features/folding/register.js'
import 'monaco-editor/features/format/register.js'
import 'monaco-editor/features/gotoError/register.js'
import 'monaco-editor/features/gotoLine/register.js'
import 'monaco-editor/features/gotoSymbol/register.js'
import 'monaco-editor/features/hover/register.js'
import 'monaco-editor/features/indentation/register.js'
import 'monaco-editor/features/lineSelection/register.js'
import 'monaco-editor/features/linesOperations/register.js'
import 'monaco-editor/features/multicursor/register.js'
import 'monaco-editor/features/quickCommand/register.js'
import 'monaco-editor/features/quickOutline/register.js'
import 'monaco-editor/features/referenceSearch/register.js'
import 'monaco-editor/features/rename/register.js'
import 'monaco-editor/features/smartSelect/register.js'
import 'monaco-editor/features/snippet/register.js'
import 'monaco-editor/features/suggest/register.js'
import 'monaco-editor/features/wordHighlighter/register.js'
import 'monaco-editor/features/wordOperations/register.js'
