defmodule Conformance.MixProject do
  use Mix.Project

  # Host harness for the Ecto conformance check. `mix compile` expands the
  # generated `use Ecto.Schema` / schema/2 DSL in lib/*.ex against the real
  # Ecto API, catching reserved-word collisions, bad field types and malformed
  # associations that a string-equality test cannot see.
  def project do
    [
      app: :conformance,
      version: "0.0.0",
      elixir: "~> 1.18",
      deps: deps()
    ]
  end

  def application, do: []

  # Exact-version pins keep resolution deterministic; mix.lock (generated by the
  # CI setup-beam job) records the hex tarball hashes. Bumps go through Renovate.
  defp deps do
    [
      {:ecto, "== 3.12.5"},
      {:ecto_sql, "== 3.12.1"}
    ]
  end
end
