/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as PrismaRouteImport } from './routes/prisma'
import { Route as SqlRouteImport } from './routes/sql'
import { Route as EnumsNameRouteImport } from './routes/enums.$name'
import { Route as ModelsNameRouteImport } from './routes/models.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrismaRoute = PrismaRouteImport.update({
  id: '/prisma',
  path: '/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const SqlRoute = SqlRouteImport.update({
  id: '/sql',
  path: '/sql',
  getParentRoute: () => rootRouteImport,
} as any)
const EnumsNameRoute = EnumsNameRouteImport.update({
  id: '/enums/$name',
  path: '/enums/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsNameRoute = ModelsNameRouteImport.update({
  id: '/models/$name',
  path: '/models/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/prisma': typeof PrismaRoute
  '/sql': typeof SqlRoute
  '/enums/$name': typeof EnumsNameRoute
  '/models/$name': typeof ModelsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/prisma': typeof PrismaRoute
  '/sql': typeof SqlRoute
  '/enums/$name': typeof EnumsNameRoute
  '/models/$name': typeof ModelsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/prisma': typeof PrismaRoute
  '/sql': typeof SqlRoute
  '/enums/$name': typeof EnumsNameRoute
  '/models/$name': typeof ModelsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/docs' | '/prisma' | '/sql' | '/enums/$name' | '/models/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/docs' | '/prisma' | '/sql' | '/enums/$name' | '/models/$name'
  id:
    | '__root__'
    | '/'
    | '/docs'
    | '/prisma'
    | '/sql'
    | '/enums/$name'
    | '/models/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsRoute: typeof DocsRoute
  PrismaRoute: typeof PrismaRoute
  SqlRoute: typeof SqlRoute
  EnumsNameRoute: typeof EnumsNameRoute
  ModelsNameRoute: typeof ModelsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prisma': {
      id: '/prisma'
      path: '/prisma'
      fullPath: '/prisma'
      preLoaderRoute: typeof PrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sql': {
      id: '/sql'
      path: '/sql'
      fullPath: '/sql'
      preLoaderRoute: typeof SqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enums/$name': {
      id: '/enums/$name'
      path: '/enums/$name'
      fullPath: '/enums/$name'
      preLoaderRoute: typeof EnumsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models/$name': {
      id: '/models/$name'
      path: '/models/$name'
      fullPath: '/models/$name'
      preLoaderRoute: typeof ModelsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsRoute: DocsRoute,
  PrismaRoute: PrismaRoute,
  SqlRoute: SqlRoute,
  EnumsNameRoute: EnumsNameRoute,
  ModelsNameRoute: ModelsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
