// Compiles the Kotlin Hekireki-Exposed writes for test/prisma/schema.prisma (src/main/kotlin/models)
// and test/prisma/exposed.prisma (src/main/kotlin/hekireki/edge, and hekireki/dsl without the DAO)
// against the real Exposed, with every warning an error, checks it is in the form ktlint writes, and
// runs the checks in Main.kt. The generated directories are regenerated by test/lang/setup.ts and
// gitignored; gradle.lockfile and gradle/verification-metadata.xml pin every dependency and its
// checksum (`gradle dependencies --write-locks`, `gradle --write-verification-metadata sha256
// installDist ktlint dependencies` from an empty GRADLE_USER_HOME, as CI starts from: a warm cache
// can leave out a POM that a cold one fetches).
plugins {
    kotlin("jvm") version "2.3.20"
    application
}

repositories {
    mavenCentral()
}

val ktlint: Configuration by configurations.creating

dependencies {
    val exposed = "1.5.0"
    implementation("org.jetbrains.exposed:exposed-core:$exposed")
    implementation("org.jetbrains.exposed:exposed-jdbc:$exposed")
    implementation("org.jetbrains.exposed:exposed-dao:$exposed")
    implementation("org.jetbrains.exposed:exposed-json:$exposed")
    implementation("org.jetbrains.exposed:exposed-migration-jdbc:$exposed")
    implementation("org.postgresql:postgresql:42.7.13")
    // cuid() / cuid(2) and ulid() defaults are generated with these.
    implementation("io.github.thibaultmeyer:cuid:2.0.5")
    implementation("com.github.f4b6a3:ulid-creator:5.2.4")
    runtimeOnly("org.slf4j:slf4j-nop:2.0.17")
    ktlint("com.pinterest.ktlint:ktlint-cli:1.8.0")
}

dependencyLocking {
    lockAllConfigurations()
}

kotlin {
    jvmToolchain(21)
    compilerOptions {
        allWarningsAsErrors.set(true)
    }
}

application {
    mainClass.set("MainKt")
    // A zone with an offset and a daylight-saving gap, so that a value converted through the JVM's
    // time zone anywhere between the model and the database shows.
    applicationDefaultJvmArgs = listOf("-Duser.timezone=America/New_York")
}

tasks.register<JavaExec>("ktlint") {
    description = "Checks that the generated Kotlin is already in the form ktlint writes."
    classpath = ktlint
    mainClass.set("com.pinterest.ktlint.Main")
    args("src/main/kotlin/models/**/*.kt", "src/main/kotlin/hekireki/**/*.kt")
}
