import type { DMMF } from '@prisma/generator-helper'
import { getDMMF } from '@prisma/get-dmmf'
import type { GetDMMFError } from '@prisma/get-dmmf'
import { describe, expect, it } from 'vite-plus/test'

import { seedSchemaCode } from './seed.js'

const SCHEMA = `
datasource db {
  provider = "postgresql"
}

enum Role {
  ADMIN
  VIEWER @map("viewer")
}

model User {
  id    Int    @id @default(autoincrement())
  role  Role
  tags  Tag[]
  posts Post[]
}

model Post {
  id       Int  @id @default(autoincrement())
  authorId Int
  author   User @relation(fields: [authorId], references: [id])
}

model Tag {
  id    Int    @id @default(autoincrement())
  users User[]
}
`

function datamodel() {
  const result: DMMF.Document | GetDMMFError = getDMMF({ datamodel: [['schema.prisma', SCHEMA]] })
  if ('type' in result) throw new Error(result.error.message)
  return result.datamodel
}

describe('seedSchemaCode', () => {
  it('writes every model, field, unique key and enum member as one defineSchema literal', () => {
    expect(seedSchemaCode(datamodel())).toBe(
      `// Generated by hekireki-seed. Do not edit: \`prisma generate\` rewrites it.
import { defineSchema } from 'hekireki'

/** The Prisma schema as \`defineConfig(schema, { ... })\` in hekireki.config.ts checks the rules against. */
export const schema = defineSchema({
  models: [{ name: 'User', fields: [{ name: 'id', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: true }, { name: 'role', kind: 'enum', type: 'Role', isList: false, isRequired: true, hasDefault: false }, { name: 'tags', kind: 'object', type: 'Tag', isList: true, isRequired: true, hasDefault: false, relationName: 'TagToUser' }, { name: 'posts', kind: 'object', type: 'Post', isList: true, isRequired: true, hasDefault: false, relationName: 'PostToUser' }], uniques: [['id']] }, { name: 'Post', fields: [{ name: 'id', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: true }, { name: 'authorId', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: false }, { name: 'author', kind: 'object', type: 'User', isList: false, isRequired: true, hasDefault: false, relationName: 'PostToUser', relationFromFields: ['authorId'] }], uniques: [['id']] }, { name: 'Tag', fields: [{ name: 'id', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: true }, { name: 'users', kind: 'object', type: 'User', isList: true, isRequired: true, hasDefault: false, relationName: 'TagToUser' }], uniques: [['id']] }],
  enums: [{ name: 'Role', values: ['ADMIN', 'VIEWER'] }],
})
`,
    )
  })

  it('escapes quotes in names', () => {
    const code = seedSchemaCode({
      models: [
        {
          name: "It's",
          dbName: null,
          schema: null,
          fields: [],
          uniqueFields: [],
          uniqueIndexes: [],
          primaryKey: null,
        },
      ],
      enums: [],
      types: [],
      indexes: [],
    })
    expect(code).toContain("{ name: 'It\\'s', fields: [], uniques: [] }")
  })
})
