import type { DMMF } from '@prisma/generator-helper'
import { getDMMF } from '@prisma/get-dmmf'
import type { GetDMMFError } from '@prisma/get-dmmf'
import { describe, expect, it } from 'vite-plus/test'

import { seedSchemaCode } from './seed.js'

const SCHEMA = `
datasource db {
  provider = "postgresql"
}

enum Role {
  ADMIN
  VIEWER @map("viewer")
}

model User {
  id    Int    @id @default(autoincrement())
  role  Role
  tags  Tag[]
  posts Post[]
}

model Post {
  id       Int  @id @default(autoincrement())
  authorId Int
  author   User @relation(fields: [authorId], references: [id])
}

model Tag {
  id    Int    @id @default(autoincrement())
  users User[]
}
`

function datamodel() {
  const result: DMMF.Document | GetDMMFError = getDMMF({ datamodel: [['schema.prisma', SCHEMA]] })
  if ('type' in result) throw new Error(result.error.message)
  return result.datamodel
}

describe('seedSchemaCode', () => {
  it('writes every model, field, unique key and enum member as one defineSchema literal', () => {
    expect(seedSchemaCode(datamodel())).toBe(
      `// Generated by hekireki-seed. Do not edit: \`prisma generate\` rewrites it.
import { defineSchema } from 'hekireki'

/** The Prisma schema as \`defineConfig(schema, { ... })\` in hekireki.config.ts checks the rules against. */
export const schema = defineSchema({
  models: [{ name: 'User', fields: [{ name: 'id', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: true }, { name: 'role', kind: 'enum', type: 'Role', isList: false, isRequired: true, hasDefault: false }, { name: 'tags', kind: 'object', type: 'Tag', isList: true, isRequired: true, hasDefault: false, relationName: 'TagToUser' }, { name: 'posts', kind: 'object', type: 'Post', isList: true, isRequired: true, hasDefault: false, relationName: 'PostToUser' }], uniques: [['id']] }, { name: 'Post', fields: [{ name: 'id', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: true }, { name: 'authorId', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: false }, { name: 'author', kind: 'object', type: 'User', isList: false, isRequired: true, hasDefault: false, relationName: 'PostToUser', relationFromFields: ['authorId'] }], uniques: [['id']] }, { name: 'Tag', fields: [{ name: 'id', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: true }, { name: 'users', kind: 'object', type: 'User', isList: true, isRequired: true, hasDefault: false, relationName: 'TagToUser' }], uniques: [['id']] }],
  enums: [{ name: 'Role', values: ['ADMIN', 'VIEWER'] }],
})
`,
    )
  })

  it('escapes quotes in names', () => {
    const code = seedSchemaCode({
      models: [
        {
          name: "It's",
          dbName: null,
          schema: null,
          fields: [],
          uniqueFields: [],
          uniqueIndexes: [],
          primaryKey: null,
        },
      ],
      enums: [],
      types: [],
      indexes: [],
    })
    expect(code).toContain("{ name: 'It\\'s', fields: [], uniques: [] }")
  })
})

describe('seedSchemaCode, the shapes it has to get right', () => {
  it('writes composite keys, mapped uniques, enum lists and self relations, and leaves out what Prisma ignores', () => {
    const result: DMMF.Document | GetDMMFError = getDMMF({
      datamodel: [
        [
          'schema.prisma',
          `datasource db {
  provider = "postgresql"
}

enum Role {
  ADMIN
  VIEWER @map("viewer")
}

model Warehouse {
  country String
  code    String
  stocks  Stock[]

  @@id([country, code])
}

model Stock {
  id        Int       @id @default(autoincrement())
  country   String
  code      String
  warehouse Warehouse @relation(fields: [country, code], references: [country, code])
  note      Unsupported("geometry")?
  secret    String    @ignore
  slug      String?   @unique
  a         Int
  b         Int
  roles     Role[]
  meta      Json?

  @@unique([a, b], map: "ab_key")
}

model Ghost {
  id Int @id

  @@ignore
}

model Category {
  id        Int        @id @default(autoincrement())
  related   Category[] @relation("rel")
  relatedBy Category[] @relation("rel")
}
`,
        ],
      ],
    })
    if ('type' in result) throw new Error(result.error.message)
    expect(seedSchemaCode(result.datamodel)).toBe(
      `// Generated by hekireki-seed. Do not edit: \`prisma generate\` rewrites it.
import { defineSchema } from 'hekireki'

/** The Prisma schema as \`defineConfig(schema, { ... })\` in hekireki.config.ts checks the rules against. */
export const schema = defineSchema({
  models: [{ name: 'Warehouse', fields: [{ name: 'country', kind: 'scalar', type: 'String', isList: false, isRequired: true, hasDefault: false }, { name: 'code', kind: 'scalar', type: 'String', isList: false, isRequired: true, hasDefault: false }, { name: 'stocks', kind: 'object', type: 'Stock', isList: true, isRequired: true, hasDefault: false, relationName: 'StockToWarehouse' }], uniques: [['country', 'code']] }, { name: 'Stock', fields: [{ name: 'id', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: true }, { name: 'country', kind: 'scalar', type: 'String', isList: false, isRequired: true, hasDefault: false }, { name: 'code', kind: 'scalar', type: 'String', isList: false, isRequired: true, hasDefault: false }, { name: 'warehouse', kind: 'object', type: 'Warehouse', isList: false, isRequired: true, hasDefault: false, relationName: 'StockToWarehouse', relationFromFields: ['country', 'code'] }, { name: 'slug', kind: 'scalar', type: 'String', isList: false, isRequired: false, hasDefault: false }, { name: 'a', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: false }, { name: 'b', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: false }, { name: 'roles', kind: 'enum', type: 'Role', isList: true, isRequired: true, hasDefault: false }, { name: 'meta', kind: 'scalar', type: 'Json', isList: false, isRequired: false, hasDefault: false }], uniques: [['id'], ['slug'], ['a', 'b']] }, { name: 'Category', fields: [{ name: 'id', kind: 'scalar', type: 'Int', isList: false, isRequired: true, hasDefault: true }, { name: 'related', kind: 'object', type: 'Category', isList: true, isRequired: true, hasDefault: false, relationName: 'rel' }, { name: 'relatedBy', kind: 'object', type: 'Category', isList: true, isRequired: true, hasDefault: false, relationName: 'rel' }], uniques: [['id']] }],
  enums: [{ name: 'Role', values: ['ADMIN', 'VIEWER'] }],
})
`,
    )
  })
})
