import { Array, Result } from 'effect'

import type { makeConversions } from '../conversion.js'
import type { ModelFixes } from '../decisions.js'
import type { makeExpectedTables } from '../tables.js'
import { identityColumns } from './values.js'

/** The check's decision for one table: what it fixes, resolved against the schema and the database. */
export function resolveTable(input: {
  readonly table: ReturnType<typeof makeExpectedTables>[number]
  readonly actual: {
    readonly columns: readonly {
      readonly name: string
      readonly enumValues: readonly string[] | null
      readonly generated?: boolean
    }[]
    /** The keys the database has now: one of them tells the rows apart for a fix. */
    readonly uniques: readonly (readonly string[])[]
  }
  readonly conversionsOf: (column: string) => ReturnType<typeof makeConversions>
  readonly config: ModelFixes
}) {
  const { table, actual, config } = input
  const where = table.model
  const inDatabase = (column: string) => actual.columns.some((c) => c.name === column)
  const fieldOf = (field: string) => table.columns.find((c) => c.field === field)
  const fields = Object.entries(config.fields ?? {}).map(([field, fix]) => {
    const column = fieldOf(field)
    if (column === undefined) {
      return Result.fail(`${where}.${field}: ${table.model} has no field ${field}.`)
    }
    if (!inDatabase(column.column)) {
      // An added column has no values yet: `nulls` fills the rows already there, and nothing
      // else has anything to act on.
      const others = (['values', 'invalid', 'duplicates', 'convert'] as const).filter(
        (key) => fix[key] !== undefined,
      )
      if (
        others.length > 0 ||
        (fix.nulls === undefined && fix.renamedFrom === undefined && fix.movedFrom === undefined)
      ) {
        return Result.fail(
          `${where}.${field}: the migration adds ${table.model}.${field}; only filling the rows already there applies to it.`,
        )
      }
      if (fix.movedFrom !== undefined && fix.nulls !== undefined) {
        return Result.fail(
          `${where}.${field}: the values moved from ${fix.movedFrom.model}.${fix.movedFrom.column} fill it; keep the move or the fill.`,
        )
      }
      return Result.succeed({ column, fix, added: true })
    }
    if (fix.movedFrom !== undefined) {
      return Result.fail(
        `${where}.${field}: ${table.table} has a column ${column.column} already; values are moved into a column the migration adds.`,
      )
    }
    // Every fix of a column that has values is an UPDATE of it, which the database refuses here.
    if (actual.columns.find((c) => c.name === column.column)?.generated === true) {
      return Result.fail(
        `${where}.${field}: ${table.table}.${column.column} is generated by the database, which refuses a statement that writes to it. Change what it is generated from, or settle its rows by hand.`,
      )
    }
    return Result.succeed({ column, fix, added: false })
  })
  const [fieldErrors, fixedColumns] = Array.separate(fields)
  const relations = Object.entries(config.relations ?? {}).map(([field, fix]) => {
    const foreignKey = table.foreignKeys.find((fk) => fk.field === field)
    return foreignKey === undefined
      ? Result.fail(
          `${where}.${field}: ${table.model} has no relation ${field} that holds a foreign key.`,
        )
      : Result.succeed({ foreignKey, fix })
  })
  const [relationErrors, related] = Array.separate(relations)
  const duplicateSettings = [
    ...fixedColumns.flatMap((entry) =>
      entry.fix.duplicates === undefined
        ? []
        : [
            {
              path: `${where}.${entry.column.field}`,
              fields: [entry.column.field],
              fix: entry.fix.duplicates,
            },
          ],
    ),
    ...(config.unique ?? []).map((unique) => ({
      path: `${where}.${unique.fields.join(', ')}`,
      fields: unique.fields,
      fix: unique,
    })),
  ]
  const duplicateResults = duplicateSettings.map((setting) => {
    const columns = setting.fields.map((field) => fieldOf(field)?.column ?? null)
    // The unique key over the same columns, in any order.
    const key = table.uniques.find(
      (unique) =>
        unique.columns.length === columns.length &&
        unique.columns.every((column) => columns.includes(column)),
    )
    const order =
      setting.fix.orderBy === undefined ? null : (fieldOf(setting.fix.orderBy)?.column ?? null)
    const errors = [
      ...(key === undefined || columns.includes(null)
        ? [`${setting.path}: ${table.model} has no unique key over ${setting.fields.join(', ')}.`]
        : []),
      ...(setting.fix.orderBy !== undefined && order === null
        ? [
            `${setting.path}: ${table.model} has no field ${setting.fix.orderBy} to order the duplicates by.`,
          ]
        : []),
      ...(table.primaryKey.length === 0
        ? [`${setting.path}: ${table.model} has no primary key to tell its rows apart.`]
        : []),
      ...(key !== undefined &&
      table.primaryKey.length > 0 &&
      identityColumns(actual, table.primaryKey, key.columns) === null
        ? [
            `${setting.path}: ${table.model} has no key that tells the rows of one ${setting.fields.join(', ')} apart, so the plan cannot keep one of them and drop the rest. Settle these rows by hand before the migration.`,
          ]
        : []),
    ]
    return key === undefined || errors.length > 0
      ? Result.fail(errors)
      : Result.succeed({
          key: key.columns,
          fields: setting.fields,
          order: order === null ? table.primaryKey : [order],
          fix: setting.fix,
        })
  })
  const [duplicateErrors, duplicates] = Array.separate(duplicateResults)
  const columnErrors = fixedColumns.flatMap(({ column, fix }) => {
    const path = `${where}.${column.field}`
    const blocking = input
      .conversionsOf(column.column)
      .filter((c) => c.severity === 'blocking' && c.kind !== 'column-recreated')
    // With `convert`, the conversion is the decision's own: what the type refuses is its answer,
    // and the error below says to keep one of the two.
    const invalid = fix.convert === undefined ? fix.invalid : undefined
    const invalidErrors =
      invalid === 'clamp' && !blocking.some((c) => c.bounds !== null)
        ? [
            `${path}: clamp applies to values out of range, and the type change of ${table.model}.${column.field} has none.`,
          ]
        : invalid === 'truncate' && !blocking.some((c) => c.length !== null)
          ? [
              `${path}: truncate applies to values too long, and the type change of ${table.model}.${column.field} has none.`,
            ]
          : []
    const members = column.enumMembers ?? []
    const valueErrors = Object.entries(fix.values ?? {}).flatMap(([stored, member]) => {
      if (column.kind !== 'enum') {
        return [`${path}: ${table.model}.${column.field} is not an enum.`]
      }
      return members.some((m) => m.name === member)
        ? []
        : [`${path}: ${member}, for ${stored}, is not a member of ${column.type}.`]
    })
    const convertErrors =
      fix.convert !== undefined && fix.invalid !== undefined
        ? [
            `${path}: a conversion says how every value becomes the new type, which leaves what becomes of the values it refuses nothing to do; keep one of the two.`,
          ]
        : []
    return [...invalidErrors, ...valueErrors, ...convertErrors]
  })
  return {
    errors: [...fieldErrors, ...columnErrors, ...relationErrors, ...duplicateErrors.flat()],
    columns: fixedColumns,
    relations: related.flatMap((entry) =>
      entry.fix.orphans === undefined
        ? []
        : [{ foreignKey: entry.foreignKey, orphans: entry.fix.orphans }],
    ),
    duplicates,
  }
}

/** Whether the only fixes of a table the migration creates are values moved into it, which its rows are made from. */
export function onlyMoves(config: ModelFixes) {
  return (
    config.relations === undefined &&
    config.unique === undefined &&
    Object.values(config.fields ?? {}).every(
      (fix) =>
        fix.movedFrom !== undefined && Object.keys(fix).every((name) => name === 'movedFrom'),
    )
  )
}
